package com.bbbbb.pay.gateway.service.impl;

import com.bbbbb.common.framework.util.JsonUtils;
import com.bbbbb.pay.channel.baofu.BaofuBindCard;
import com.bbbbb.pay.common.pay.BindCard;
import com.bbbbb.pay.common.pay.result.CardInfoResult;
import com.bbbbb.pay.gateway.form.bank.CardForm;
import com.bbbbb.pay.gateway.result.bank.CardInfo;
import com.bbbbb.pay.gateway.service.CardService;
import org.springframework.beans.BeanUtils;

import org.springframework.stereotype.Service;



@Service
public class CardServiceImpl implements CardService{


    @Override
    public CardInfo getCardInfo(CardForm form) {
        BindCard bindCard=new BaofuBindCard();

        String configJson="{\"privateKey\":\"MIIITgIBAzCCCAoGCSqGSIb3DQEHAaCCB/sEggf3MIIH8zCCA8QGCSqGSIb3DQEHAaCCA7UEggOxMIIDrTCCA6kGCyqGSIb3DQEMCgECoIICtjCCArIwHAYKKoZIhvcNAQwBAzAOBAgxaEKkREXrGQICB9AEggKQ0EBLiurm2gx5hBkL7jKCi+fVv58HIagPEa2yFKCuXkVkSHlpf6nhI7Tg+/QBwegKH94DNvlqL0EG0EZHgJNu5Q0qasyCMwZlFLTAyV6VwioYaa5DE8CfFWOxoxxP7DEim/iYI14tQCu+mnEdyz5v5qIq6KcyVgeWGeHU+CxQUAWQYRrOQvP1QBCykekhvvb6EJ7BkCjrhHzN3Mb+daYZz+1GWyAWoWG/HjxgTaEqrpc6e1iNdvG7VrgKouGfwiFh0V0yrIJ0JQSWL/k+6QnWRlVH2AQQ2kSnwOwkdwgEOpLuDd4GgjETuq47Cr5xw511PCN4mB/FkawIaRlyTVM4NL7PQnH33vv91TseaNv39VgbdXs+TncvPoSNHv/tlK/hqkZgPOXj+PoCz94bWYLR/Yfl3OzZunH8Y8e4O+2uU4tTbSc6nEwS2yloHxW/8fjQldgGGeEQ17wPZuVg2874A5tRwjK1/eDxdmdymqRVjtPFb7QT1B+QEdCy6AOBmieJ1GwmLJOZro51SLI8/armaAEPNUUxZ44yLnf7TRgGGSpe0okTX7xEXQrApQnr5yGWxeTnhwENuZEpXESwglPBiNDsGfHxFGdWR9KrxkLVoUCw8s1uXlQrjNW+aReDQs9puTsssdJPB7md1Xxe+aYefIjMyT4svxWm+ZQaloEVN9lWKf/z4Y6NU7kRKDC+905IK6wbwvev0aipqNeU/wsMLKPulyXkqEShIvZdJAu5L9FJrYw2XByjhyaGSVoXQuOQtg35VpkS9EnVtzE7qIoEZlbAK8HnI7QrV0OLzEHKQcKSJaWEObrrzus2KpsCLu+odUbKgOWeZM1Kx+oywWl/SHzjoFSwhn9ZmrmHXtBptl0xgd8wEwYJKoZIhvcNAQkVMQYEBAEAAAAwWwYJKoZIhvcNAQkUMU4eTAB7ADkAMwBEADcAQwA3ADMAQQAtADUANQAwADYALQA0ADcAOQAyAC0AOQAwAEMAMQAtADEANwBFADMARgA0ADMAOQA2ADMAMgAxAH0wawYJKwYBBAGCNxEBMV4eXABNAGkAYwByAG8AcwBvAGYAdAAgAEUAbgBoAGEAbgBjAGUAZAAgAEMAcgB5AHAAdABvAGcAcgBhAHAAaABpAGMAIABQAHIAbwB2AGkAZABlAHIAIAB2ADEALgAwMIIEJwYJKoZIhvcNAQcGoIIEGDCCBBQCAQAwggQNBgkqhkiG9w0BBwEwHAYKKoZIhvcNAQwBBjAOBAiietjzqB/XNwICB9CAggPgkiiHl2N4Q0OeyQYQJFHUPv/hB16yabZaIGl1MR2iqW+Yja+O2yPhIhiVxm0E/eLGA6lT0j6XLf7LInL8MoAGSybSGMMROKH+8SQs8VmeXoGupucBd/cKxuWhKB0Ylgc6dGi+FLI1MWFFwGy/KItlSqTXpvsIK3IqHTfCrS5hkIpDJpnW4ZEAn+UzVnN8DPpvPz16C0Def7H4x8oqxSG3tIedKHt7h3h492pS3i54xL99WVYQinhnvES/vaabFVblS4qNqAvktj4QRoyaSGBXPzmgODvTsS6SmKzM6TpxTo/OabACeWTuZuvSFbLXF2FnBTHvN4JW8/0PiWrTC582osvkj3c7JbXvnw7bnwoCyrh3jvv7DjnYJIo2CAs85jsY2LzhwWtVEYpSqQbS5eg4qlbqf5YPdaZGr/v3d2wi7uDZSVAoGRTn7jNdhkNbklxPuzn7iN41qJVhgy7XCVIsSQlFv3kBKJK+VbeyToG24UwktKS+OmKFqpO5LiGMhUZeVK1OE5B+VKdRYarTRSqNQS8PnkRcqtCJFIG7d671ypxCCdlrBaNJaHWIWRw+ZHoEN+QvPXKoIrknT0plVeahX9QeFXDiUHMMoXOenDkVm2wwojstH8whw51tzm5vRvN2Q6mTgzYylm4BvMSQkpwoBvIBx8A0Cl3RARD8OXxoK5fcUesQVkpeK3nNGaghcNwMiH8FW8a9XwF7kz7UiXnpFOADShhWdtGwejEs0QsE53rZHnS7dsd3WOIqTrMIJNcfSK+Nu2BOJDp0WaBHhdKLvdevUavcfwGbZAllNXe22W32Z+fjHc4BIIxQ3Tp8usMFeB5uC+wdTKfEAy3Ac0mrnBQkqJRSc6kWcCJ8Wwh/dUQfdBnQ9IiYxPn5gFyOw8TeSJbJaTCmvgzOJAbrjgAdqpggRjX4OmuCS6T8c7qDHTjEayRS3hPQnTwRZV3ltkwzVAeZxsgubVXVwInyvK1roLOlZWHyXWtnXMBMZjL7XeR7DWXI9m17uLOzkYa81iuO/89rGU6l15uQwhb4qCY0ycgd267gf+7MctYQX3gfZtgz3OMfjTTBWpLH4eYqJUv4Dy2Ou1oKdB34MgV1+JKuc+Ro5uZdWFnI5souHN9/IrexqOzPFwe5e/8C4v/KlvR+Z3ghx4eeTCGrJu1zmeYhV/YyyiXH4ohWpy78Hi5jDQv1TibYoP0b1yk6V3zGZAWeNXUdX+3wNaHH8Hnmzo7VrxMbelOgNh17WnPdf91u6sygg9mCGBWNqYc0QlsjAd0k+gYMqs4EfKPIDR2w0CBgCZXq9OdJ0nKv47lfvmsHAjYwOzAfMAcGBSsOAwIaBBRqlGEQ5ff2BfkXqB+xLJhXYBcnMAQUEsmrXJ7qO8UBh1Mi+GyslYOr3NkCAgfQ\",\"publicKey\":\"-----BEGIN CERTIFICATE-----\\nMIIDgDCCAmigAwIBAgIFEFmDdYIwDQYJKoZIhvcNAQEFBQAwITELMAkGA1UEBhMC\\nQ04xEjAQBgNVBAoTCUNGQ0EgT0NBMTAeFw0xNjEwMjQwNzIzMjRaFw0yMTEwMjQw\\nNzIzMjRaMHExCzAJBgNVBAYTAkNOMRIwEAYDVQQKEwlDRkNBIE9DQTExDzANBgNV\\nBAsTBkJhb2ZvbzEZMBcGA1UECxMQT3JnYW5pemF0aW9uYWwtMTEiMCAGA1UEAwwZ\\nQmFvZm9vQOWuneS7mEBaNjg4MTk5OTlAMTCBnzANBgkqhkiG9w0BAQEFAAOBjQAw\\ngYkCgYEA30bgCAY6agzuJccSKfLe/2NeOeUm2GZFuajai6CB9E0SOg6QymWuGw/f\\nXyL6rcZd/eavew1Ec2EDTeq4DgVudah6HZbI3EXt2TSxLpn6AwDMwKgSGhWpxR2V\\n1HnEiIyTOCjdWe5gUJl62UnE5acErjO0G9w+o+qGy13r0/ZZ6h0CAwEAAaOB8jCB\\n7zAfBgNVHSMEGDAWgBTR2+mIguXdGo9MqgCMvnzyqxv22TBIBgNVHSAEQTA/MD0G\\nCGCBHIbvKgEBMDEwLwYIKwYBBQUHAgEWI2h0dHA6Ly93d3cuY2ZjYS5jb20uY24v\\ndXMvdXMtMTQuaHRtMDcGA1UdHwQwMC4wLKAqoCiGJmh0dHA6Ly9jcmwuY2ZjYS5j\\nb20uY24vUlNBL2NybDQ0MDEuY3JsMAsGA1UdDwQEAwID6DAdBgNVHQ4EFgQURqt0\\nqRdCkRebpuVAmkiDlMQj95IwHQYDVR0lBBYwFAYIKwYBBQUHAwIGCCsGAQUFBwME\\nMA0GCSqGSIb3DQEBBQUAA4IBAQAHTgkQg47p4Fy5PCFcdGzX5LnHqyHK/cysjcpo\\nlHSj89/s/kX1pXU7Jqgp/FD1RJu/Ng6rmgHSNDR9ZHwapdc++PRSxDBN/+2BnR6J\\n4CoxHb0e7sjDddb7R1ceTuRXNjZuruV80j5HFycgrHSsSLI/LeZq1up0NLM+YOxt\\n/+zsnkAiGfLvRCVTlppwgfhpsT1LhdVvrDkYMedbgrA1zqL/kbXe0DIdb8kn2G8Q\\n7zR8SEYPXnWsDR2Ktno53mxKhx9kg3DQayWMudNY8qy+So0uBT1CqCsWR7SWoMpX\\nVSnKLXWBCRDqevVt4B2fpTHoo4uM4oZDggYaf14ky90d0lWH\\n-----END CERTIFICATE-----\\n\",\"priKeyPass\":\"170830\",\"terminalId\":\"38803\",\"memberId\":\"1203291\"}\n";
        bindCard.setConfig(JsonUtils.toTreeMap(configJson));
        CardInfoResult result=bindCard.cardInfo(form.getCardNo());
        CardInfo cardInfo=new CardInfo();
        BeanUtils.copyProperties(result,cardInfo);
        return cardInfo;
    }
}
